export class queryList {
  GET_STORE_LIST_QUERY: string =
    `SELECT STORE_ID, STORE_NAME, STORE_CODE FROM BMS.STORE`;
  SAVE_STORE_QUERY: string =
    `INSERT INTO BMS.STORE (STORE_NAME, STORE_CODE, ADDRESS , CREATED_ON , CREATED_By) VALUES($1, $2, $3, $4, $5)`;

  GET_BOOK_LIST_QUERY: string =
    `SELECT BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER FROM BMS.BOOK`;
  SAVE_BOOK_QUERY: string = ``;

  GET_BOOK_DETAILS_QUERY: string = `SELECT BOOK_ID, BOOK_TITLE, BOOK_DESCRIPTION, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_PAGES, BOOK.STORE_CODE, store.store_name , store.address  FROM BMS.BOOK INNER JOIN  BMS.STORE ON BOOK.STORE_CODE  = STORE.STORE_CODE WHERE BOOK_ID =$1`;
}